#!/bin/bash
cat <<EOF
Welcome to VisionEval!

This Docker image can run VERSPM or VERPAT on your data.  You can also
use it to run a few canned models.

To run it:

docker run -v /Data:/path/to/MyData VisionEval VERSPM # or VERPAT

Your "MyData" folder should contain "defs" and "inputs" per the
instructions for setting up the models.  If it does not, it will be as
if you provided the default test data argument as described below.

You can provide additional arguments to try out test models. So for example:

docker run -v /Data:/path/to/MyData VisionEval VERSPM Test1 # or Test2
docker run -v /Data:/path/to/MyData VisionEval VERPAT Test 

If your "MyData" folder is empty or if you do not provide the -v
(volume) parameter to link visioneval to your data, you will get a copy
of the (default) test setup and output.

If you do not provide the -v (volume) Data parameter, you will get a
copy of the (default) test output, the test model will run, but the data
will remain locked in the container (you can extract it after the container
has stopped with the “docker cp” command, reaching for /Data).

If your "MyData" has anything in it but it's not obviously a scenario
setup, docker will create a subdirectory (called e.g. "Test" or
"Test1"), copy the test setup to it and run the model in that
subdirectory.
EOF
