#!/bin/bash

# This script will change to ve.test directory and proceed to
# run a list of tests generated by "setup-tests.R" using Rscript
# to execute each of them in turn.  Even if run from make, the
# test results are logged.

cd ${VE_TEST}

echo Running tests scripts in $(pwd)
. ./do-tests.sh 2>&1 | tee tests.log
echo Finished tests
